In [1]:
#1.Data Extraction-Reading data from all four input CSV files and handling errors for missing files.

import csv
import os

def read_csv(file_path):
    # Checking if the file exists
    if not os.path.isfile(file_path):
        print(f"Error: {file_path} not found.")
        return []
    # if file exists, read the data
    with open(file_path, mode='r') as file:
            reader = csv.DictReader(file)
            return list(reader)
   
        
#reading data from all the files and printing first 5 entries
sales_data = read_csv(r'E:\Hero Vired\Python ETL project\sales.csv')
print("Sales Data (first 5 entries):")
print(sales_data[0:5])

products_data = read_csv(r'E:\Hero Vired\Python ETL project\Product.csv')
print("\nProducts Data (first 5 entries):")
print(products_data[0:5])

customers_data = read_csv(r'E:\Hero Vired\Python ETL project\Customer.csv')
print("\nCustomers Data (first 5 entries):")
print(customers_data[0:5])

employees_data = read_csv(r'E:\Hero Vired\Python ETL project\employee.csv')
print("\nEmployees Data (first 5 entries):")
print(employees_data[0:5])

Sales Data (first 5 entries):
[{'sale_id': '1001', 'date': '01-09-2024', 'customer_id': 'C101', 'product_id': 'P201', 'quantity': '2', 'price': '29.99'}, {'sale_id': '1002', 'date': '02-09-2024', 'customer_id': 'C102', 'product_id': 'P202', 'quantity': '1', 'price': '49.99'}, {'sale_id': '1003', 'date': '02-09-2024', 'customer_id': 'C103', 'product_id': 'P203', 'quantity': '3', 'price': '15.99'}, {'sale_id': '1004', 'date': '03-09-2024', 'customer_id': 'C101', 'product_id': 'P204', 'quantity': '1', 'price': '99.99'}, {'sale_id': '1005', 'date': '04-09-2024', 'customer_id': 'C104', 'product_id': 'P201', 'quantity': '2', 'price': '29.99'}]

Products Data (first 5 entries):
[{'product_id': 'P201', 'product_name': 'Wireless Mouse', 'category': 'Electronics', 'cost_price': '20'}, {'product_id': 'P202', 'product_name': 'LED Desk Lamp', 'category': 'Home & Office', 'cost_price': '35'}, {'product_id': 'P203', 'product_name': 'Notebook Set', 'category': 'Stationery', 'cost_price': '10'}, {'product_id': 'P204', 'product_name': 'Bluetooth Speaker', 'category': 'Electronics', 'cost_price': '75'}, {'product_id': 'P205', 'product_name': 'Ergonomic Chair', 'category': 'Furniture', 'cost_price': '150'}]

Customers Data (first 5 entries):
[{'customer_id': 'C101', 'name': 'Alex Johnson', 'email': 'alex.johnson@example.com', 'address': '101 Maple Street', 'join_date': '15-01-2023'}, {'customer_id': 'C102', 'name': 'Emily Davis', 'email': 'emily.davis@example.com', 'address': '202 Oak Avenue', 'join_date': '22-01-2023'}, {'customer_id': 'C103', 'name': 'Michael Brown', 'email': 'michael.brown@example.com', 'address': '303 Pine Road', 'join_date': '29-01-2023'}, {'customer_id': 'C104', 'name': 'Sophia Wilson', 'email': 'sophia.wilson@example.com', 'address': '404 Cedar Lane', 'join_date': '05-02-2023'}, {'customer_id': 'C105', 'name': 'Daniel Smith', 'email': 'daniel.smith@example.com', 'address': '505 Birch Drive', 'join_date': '12-02-2023'}]

Employees Data (first 5 entries):
[{'employee_id': 'E001', 'name': 'Emily Johnson', 'department': 'Sales', 'hire_date': '15-01-2018', 'salary': '65000'}, {'employee_id': 'E002', 'name': 'Michael Smith', 'department': 'Marketing', 'hire_date': '22-03-2019', 'salary': '60000'}, {'employee_id': 'E003', 'name': 'Jessica Williams', 'department': 'Finance', 'hire_date': '10-06-2017', 'salary': '70000'}, {'employee_id': 'E004', 'name': 'David Brown', 'department': 'IT', 'hire_date': '05-08-2020', 'salary': '75000'}, {'employee_id': 'E005', 'name': 'Sarah Davis', 'department': 'Human Resources', 'hire_date': '30-11-2016', 'salary': '68000'}]

In [2]:
#2. Data Transformation-To check for missing values
def check_for_missing_values(data, dataset_name):
    missing_found = False  # Flag to track if any missing values are found
    
    for i, row in enumerate(data):  # Iterate over each row in the dataset
        for key, value in row.items():  # Iterate over each key (column) in the row
            # Check for None or empty string
            if value is None or value == '':
                print(f"Missing value found in {dataset_name}, row {i + 1}, column '{key}': {value}")
                missing_found = True  # Set the flag to True if a missing value is found
    
    if not missing_found:
        print(f"No missing values found in the dataset: {dataset_name}.")

# 
sales_data = read_csv(r'E:\Hero Vired\Python ETL project\sales.csv')
check_for_missing_values(sales_data, "sales_data")

products_data = read_csv(r'E:\Hero Vired\Python ETL project\Product.csv')
check_for_missing_values(products_data, "products_data")

customers_data = read_csv(r'E:\Hero Vired\Python ETL project\Customer.csv')
check_for_missing_values(customers_data, "customers_data")

employees_data = read_csv(r'E:\Hero Vired\Python ETL project\employee.csv')
check_for_missing_values(employees_data, "employees_data")

No missing values found in the dataset: sales_data.
No missing values found in the dataset: products_data.
No missing values found in the dataset: customers_data.
No missing values found in the dataset: employees_data.

In [5]:
#function to count missing values
def count_missing_values(data):
    missing_count = 0
    for row in data:
        for key in row:
            if row[key] == '':  # Check for empty strings
                missing_count += 1
    return missing_count

# Function to handle missing values
def handle_missing_values(data, default_value=None):
    """Replace missing values (empty strings) in the dataset with a default value."""
    for row in data:
        for key in row:
            if row[key] == '':  # Check for empty strings
                row[key] = default_value  # Replace with the default value
    return data

# Count missing values before handling
print("Missing values before handling:")
print(f"Sales Data: {count_missing_values(sales_data)}")
print(f"Products Data: {count_missing_values(products_data)}")
print(f"Customers Data: {count_missing_values(customers_data)}")
print(f"Employees Data: {count_missing_values(employees_data)}")

# Handle missing values
sales_data = handle_missing_values(sales_data)
products_data = handle_missing_values(products_data)
customers_data = handle_missing_values(customers_data)
employees_data = handle_missing_values(employees_data)


# Count missing values after handling
print("\nMissing values after handling:")
print(f"Sales Data: {count_missing_values(sales_data)}")
print(f"Products Data: {count_missing_values(products_data)}")
print(f"Customers Data: {count_missing_values(customers_data)}")
print(f"Employees Data: {count_missing_values(employees_data)}")

Missing values before handling:
Sales Data: 0
Products Data: 0
Customers Data: 0
Employees Data: 0

Missing values after handling:
Sales Data: 0
Products Data: 0
Customers Data: 0
Employees Data: 0

In [4]:
#To correct data types through convert_value.
from datetime import datetime
import csv

def convert_value(value, target_type):
    """Convert value to the specified target type."""
    if value is None or value == '':
        return None  # or some default value if you prefer
    try:
        if target_type == int:
            return int(value)
        elif target_type == float:
            return float(value)
        elif target_type == datetime:
            print(f"Converting date: '{value}'")
            return datetime.strptime(value.strip(), '%d-%m-%Y')  # Adjust format as needed
        else:
            return str(value)  # Default to string for any other type
    except ValueError as e:
        print(f"Error converting value '{value}' to {target_type}: {e}")
        return None 
    
#To correct data types
def convert_data_types(sales_data, products_data, customers_data, employees_data):
    # Convert data types for sales_data
    for row in sales_data:
        row['sale_id'] = convert_value(row['sale_id'], int)  # Assuming sale_id is still an integer
        row['customer_id'] = str(row['customer_id'])  # Keep customer_id as a string
        row['product_id'] = str(row['product_id'])  # Keep product_id as a string
        row['quantity'] = convert_value(row['quantity'], int)
        row['price'] = convert_value(row['price'], float)
        row['date'] = convert_value(row['date'], datetime)

    # Convert data types for products_data
    for row in products_data:
        row['product_id'] = str(row['product_id'])  # Keep product_id as a string
        row['product_name'] = convert_value(row['product_name'], str)
        row['category'] = convert_value(row['category'], str)
        row['cost_price'] = convert_value(row['cost_price'], float)

    # Convert data types for customers_data
    for row in customers_data:
        row['customer_id'] = str(row['customer_id'])  # Keep customer_id as a string
        row['name'] = convert_value(row['name'], str)
        row['email'] = convert_value(row['email'], str)
        row['address'] = convert_value(row['address'], str)
        row['join_date'] = convert_value(row['join_date'], datetime)

    # Convert data types for employees_data
    for row in employees_data:
        row['employee_id'] = convert_value(row['employee_id'], int)  # Assuming employee_id is still an integer
        row['name'] = convert_value(row['name'], str)
        row['department'] = convert_value(row['department'], str)
        row['hire_date'] = convert_value(row['hire_date'], datetime)
        row['salary'] = convert_value(row['salary'], float)


# Correct data types
convert_data_types(sales_data, products_data, customers_data, employees_data)
print("First 5 rows of sales_data:")
for row in sales_data[:5]:
    print(row)
    
print("\nFirst 5 rows of products_data:")
for row in products_data[:5]:
    print(row)

print("\nFirst 5 rows of customers_data:")
for row in customers_data[:5]:
    print(row)

print("\nFirst 5 rows of employees_data:")
for row in employees_data[:5]:
    print(row)

Converting date: '01-09-2024'
Converting date: '02-09-2024'
Converting date: '02-09-2024'
Converting date: '03-09-2024'
Converting date: '04-09-2024'
Converting date: '05-09-2024'
Converting date: '06-09-2024'
Converting date: '07-09-2024'
Converting date: '08-09-2024'
Converting date: '09-09-2024'
Converting date: '10-09-2024'
Converting date: '11-09-2024'
Converting date: '12-09-2024'
Converting date: '13-09-2024'
Converting date: '14-09-2024'
Converting date: '15-09-2024'
Converting date: '16-09-2024'
Converting date: '17-09-2024'
Converting date: '18-09-2024'
Converting date: '19-09-2024'
Converting date: '20-09-2024'
Converting date: '21-09-2024'
Converting date: '22-09-2024'
Converting date: '23-09-2024'
Converting date: '24-09-2024'
Converting date: '25-09-2024'
Converting date: '26-09-2024'
Converting date: '27-09-2024'
Converting date: '28-09-2024'
Converting date: '29-09-2024'
Converting date: '30-09-2024'
Converting date: '01-10-2024'
Converting date: '02-10-2024'
Converting date: '03-10-2024'
Converting date: '04-10-2024'
Converting date: '05-10-2024'
Converting date: '06-10-2024'
Converting date: '07-10-2024'
Converting date: '08-10-2024'
Converting date: '09-10-2024'
Converting date: '10-10-2024'
Converting date: '11-10-2024'
Converting date: '12-10-2024'
Converting date: '13-10-2024'
Converting date: '14-10-2024'
Converting date: '15-10-2024'
Converting date: '16-10-2024'
Converting date: '17-10-2024'
Converting date: '18-10-2024'
Converting date: '19-10-2024'
Converting date: '20-10-2024'
Converting date: '21-10-2024'
Converting date: '22-10-2024'
Converting date: '23-10-2024'
Converting date: '24-10-2024'
Converting date: '25-10-2024'
Converting date: '26-10-2024'
Converting date: '27-10-2024'
Converting date: '28-10-2024'
Converting date: '29-10-2024'
Converting date: '30-10-2024'
Converting date: '31-10-2024'
Converting date: '01-11-2024'
Converting date: '02-11-2024'
Converting date: '03-11-2024'
Converting date: '04-11-2024'
Converting date: '05-11-2024'
Converting date: '06-11-2024'
Converting date: '07-11-2024'
Converting date: '08-11-2024'
Converting date: '09-11-2024'
Converting date: '10-11-2024'
Converting date: '11-11-2024'
Converting date: '12-11-2024'
Converting date: '13-11-2024'
Converting date: '14-11-2024'
Converting date: '15-11-2024'
Converting date: '16-11-2024'
Converting date: '17-11-2024'
Converting date: '18-11-2024'
Converting date: '19-11-2024'
Converting date: '20-11-2024'
Converting date: '21-11-2024'
Converting date: '22-11-2024'
Converting date: '23-11-2024'
Converting date: '24-11-2024'
Converting date: '25-11-2024'
Converting date: '26-11-2024'
Converting date: '27-11-2024'
Converting date: '28-11-2024'
Converting date: '29-11-2024'
Converting date: '30-11-2024'
Converting date: '01-12-2024'
Converting date: '02-12-2024'
Converting date: '03-12-2024'
Converting date: '04-12-2024'
Converting date: '05-12-2024'
Converting date: '06-12-2024'
Converting date: '07-12-2024'
Converting date: '08-12-2024'
Converting date: '09-12-2024'
Converting date: '10-12-2024'
Converting date: '11-12-2024'
Converting date: '12-12-2024'
Converting date: '13-12-2024'
Converting date: '14-12-2024'
Converting date: '15-12-2024'
Converting date: '16-12-2024'
Converting date: '17-12-2024'
Converting date: '18-12-2024'
Converting date: '19-12-2024'
Converting date: '20-12-2024'
Converting date: '21-12-2024'
Converting date: '22-12-2024'
Converting date: '23-12-2024'
Converting date: '24-12-2024'
Converting date: '25-12-2024'
Converting date: '26-12-2024'
Converting date: '27-12-2024'
Converting date: '28-12-2024'
Converting date: '29-12-2024'
Converting date: '30-12-2024'
Converting date: '31-12-2024'
Converting date: '01-01-2025'
Converting date: '02-01-2025'
Converting date: '15-01-2023'
Converting date: '22-01-2023'
Converting date: '29-01-2023'
Converting date: '05-02-2023'
Converting date: '12-02-2023'
Converting date: '19-02-2023'
Converting date: '26-02-2023'
Converting date: '05-03-2023'
Converting date: '12-03-2023'
Converting date: '19-03-2023'
Converting date: '26-03-2023'
Converting date: '02-04-2023'
Converting date: '09-04-2023'
Converting date: '16-04-2023'
Converting date: '23-04-2023'
Converting date: '30-04-2023'
Converting date: '07-05-2023'
Converting date: '14-05-2023'
Converting date: '21-05-2023'
Converting date: '28-05-2023'
Converting date: '04-06-2023'
Converting date: '11-06-2023'
Converting date: '18-06-2023'
Converting date: '25-06-2023'
Converting date: '02-07-2023'
Converting date: '09-07-2023'
Converting date: '16-07-2023'
Converting date: '23-07-2023'
Converting date: '30-07-2023'
Converting date: '06-08-2023'
Converting date: '13-08-2023'
Converting date: '20-08-2023'
Converting date: '27-08-2023'
Converting date: '03-09-2023'
Converting date: '10-09-2023'
Converting date: '17-09-2023'
Converting date: '24-09-2023'
Converting date: '01-10-2023'
Converting date: '08-10-2023'
Converting date: '15-10-2023'
Converting date: '22-10-2023'
Converting date: '29-10-2023'
Converting date: '05-11-2023'
Converting date: '12-11-2023'
Converting date: '19-11-2023'
Converting date: '26-11-2023'
Converting date: '03-12-2023'
Converting date: '10-12-2023'
Converting date: '17-12-2023'
Converting date: '24-12-2023'
Converting date: '31-12-2023'
Converting date: '07-01-2024'
Converting date: '14-01-2024'
Converting date: '21-01-2024'
Converting date: '28-01-2024'
Converting date: '04-02-2024'
Converting date: '11-02-2024'
Converting date: '18-02-2024'
Converting date: '25-02-2024'
Converting date: '03-03-2024'
Converting date: '10-03-2024'
Converting date: '17-03-2024'
Converting date: '24-03-2024'
Converting date: '31-03-2024'
Converting date: '07-04-2024'
Converting date: '14-04-2024'
Converting date: '21-04-2024'
Converting date: '28-04-2024'
Converting date: '05-05-2024'
Converting date: '12-05-2024'
Converting date: '19-05-2024'
Converting date: '26-05-2024'
Converting date: '02-06-2024'
Converting date: '09-06-2024'
Converting date: '16-06-2024'
Converting date: '23-06-2024'
Converting date: '30-06-2024'
Converting date: '07-07-2024'
Converting date: '14-07-2024'
Converting date: '21-07-2024'
Converting date: '28-07-2024'
Converting date: '04-08-2024'
Converting date: '11-08-2024'
Converting date: '18-08-2024'
Converting date: '25-08-2024'
Converting date: '01-09-2024'
Converting date: '08-09-2024'
Converting date: '15-09-2024'
Converting date: '22-09-2024'
Converting date: '29-09-2024'
Converting date: '06-10-2024'
Converting date: '13-10-2024'
Converting date: '20-10-2024'
Converting date: '27-10-2024'
Converting date: '03-11-2024'
Converting date: '10-11-2024'
Converting date: '17-11-2024'
Converting date: '24-11-2024'
Converting date: '01-12-2024'
Converting date: '08-12-2024'
Error converting value 'E001' to <class 'int'>: invalid literal for int() with base 10: 'E001'
Converting date: '15-01-2018'
Error converting value 'E002' to <class 'int'>: invalid literal for int() with base 10: 'E002'
Converting date: '22-03-2019'
Error converting value 'E003' to <class 'int'>: invalid literal for int() with base 10: 'E003'
Converting date: '10-06-2017'
Error converting value 'E004' to <class 'int'>: invalid literal for int() with base 10: 'E004'
Converting date: '05-08-2020'
Error converting value 'E005' to <class 'int'>: invalid literal for int() with base 10: 'E005'
Converting date: '30-11-2016'
Error converting value 'E006' to <class 'int'>: invalid literal for int() with base 10: 'E006'
Converting date: '15-02-2019'
Error converting value 'E007' to <class 'int'>: invalid literal for int() with base 10: 'E007'
Converting date: '22-05-2018'
Error converting value 'E008' to <class 'int'>: invalid literal for int() with base 10: 'E008'
Converting date: '10-07-2020'
Error converting value 'E009' to <class 'int'>: invalid literal for int() with base 10: 'E009'
Converting date: '05-09-2017'
Error converting value 'E010' to <class 'int'>: invalid literal for int() with base 10: 'E010'
Converting date: '20-12-2015'
Error converting value 'E011' to <class 'int'>: invalid literal for int() with base 10: 'E011'
Converting date: '18-04-2018'
Error converting value 'E012' to <class 'int'>: invalid literal for int() with base 10: 'E012'
Converting date: '25-06-2019'
Error converting value 'E013' to <class 'int'>: invalid literal for int() with base 10: 'E013'
Converting date: '12-08-2017'
Error converting value 'E014' to <class 'int'>: invalid literal for int() with base 10: 'E014'
Converting date: '01-10-2020'
Error converting value 'E015' to <class 'int'>: invalid literal for int() with base 10: 'E015'
Converting date: '15-01-2016'
Error converting value 'E016' to <class 'int'>: invalid literal for int() with base 10: 'E016'
Converting date: '22-03-2019'
Error converting value 'E017' to <class 'int'>: invalid literal for int() with base 10: 'E017'
Converting date: '10-06-2018'
Error converting value 'E018' to <class 'int'>: invalid literal for int() with base 10: 'E018'
Converting date: '05-08-2017'
Error converting value 'E019' to <class 'int'>: invalid literal for int() with base 10: 'E019'
Converting date: '30-11-2020'
Error converting value 'E020' to <class 'int'>: invalid literal for int() with base 10: 'E020'
Converting date: '15-02-2016'
Error converting value 'E021' to <class 'int'>: invalid literal for int() with base 10: 'E021'
Converting date: '22-05-2019'
Error converting value 'E022' to <class 'int'>: invalid literal for int() with base 10: 'E022'
Converting date: '10-07-2018'
Error converting value 'E023' to <class 'int'>: invalid literal for int() with base 10: 'E023'
Converting date: '05-09-2017'
Error converting value 'E024' to <class 'int'>: invalid literal for int() with base 10: 'E024'
Converting date: '20-12-2020'
Error converting value 'E025' to <class 'int'>: invalid literal for int() with base 10: 'E025'
Converting date: '18-03-2016'
Error converting value 'E026' to <class 'int'>: invalid literal for int() with base 10: 'E026'
Converting date: '25-06-2019'
Error converting value 'E027' to <class 'int'>: invalid literal for int() with base 10: 'E027'
Converting date: '12-08-2018'
Error converting value 'E028' to <class 'int'>: invalid literal for int() with base 10: 'E028'
Converting date: '01-10-2017'
Error converting value 'E029' to <class 'int'>: invalid literal for int() with base 10: 'E029'
Converting date: '15-01-2020'
Error converting value 'E030' to <class 'int'>: invalid literal for int() with base 10: 'E030'
Converting date: '22-04-2016'
Error converting value 'E031' to <class 'int'>: invalid literal for int() with base 10: 'E031'
Converting date: '10-07-2019'
Error converting value 'E032' to <class 'int'>: invalid literal for int() with base 10: 'E032'
Converting date: '05-09-2018'
Error converting value 'E033' to <class 'int'>: invalid literal for int() with base 10: 'E033'
Converting date: '20-11-2017'
Error converting value 'E034' to <class 'int'>: invalid literal for int() with base 10: 'E034'
Converting date: '15-02-2020'
Error converting value 'E035' to <class 'int'>: invalid literal for int() with base 10: 'E035'
Converting date: '18-05-2016'
Error converting value 'E036' to <class 'int'>: invalid literal for int() with base 10: 'E036'
Converting date: '25-08-2019'
Error converting value 'E037' to <class 'int'>: invalid literal for int() with base 10: 'E037'
Converting date: '12-10-2018'
Error converting value 'E038' to <class 'int'>: invalid literal for int() with base 10: 'E038'
Converting date: '01-12-2017'
Error converting value 'E039' to <class 'int'>: invalid literal for int() with base 10: 'E039'
Converting date: '15-03-2020'
Error converting value 'E040' to <class 'int'>: invalid literal for int() with base 10: 'E040'
Converting date: '22-06-2016'
Error converting value 'E041' to <class 'int'>: invalid literal for int() with base 10: 'E041'
Converting date: '10-09-2019'
Error converting value 'E042' to <class 'int'>: invalid literal for int() with base 10: 'E042'
Converting date: '05-11-2018'
Error converting value 'E043' to <class 'int'>: invalid literal for int() with base 10: 'E043'
Converting date: '20-01-2017'
Error converting value 'E044' to <class 'int'>: invalid literal for int() with base 10: 'E044'
Converting date: '15-04-2020'
Error converting value 'E045' to <class 'int'>: invalid literal for int() with base 10: 'E045'
Converting date: '18-07-2016'
Error converting value 'E046' to <class 'int'>: invalid literal for int() with base 10: 'E046'
Converting date: '25-10-2019'
Error converting value 'E047' to <class 'int'>: invalid literal for int() with base 10: 'E047'
Converting date: '12-12-2018'
Error converting value 'E048' to <class 'int'>: invalid literal for int() with base 10: 'E048'
Converting date: '01-02-2017'
Error converting value 'E049' to <class 'int'>: invalid literal for int() with base 10: 'E049'
Converting date: '15-05-2020'
Error converting value 'E050' to <class 'int'>: invalid literal for int() with base 10: 'E050'
Converting date: '22-08-2016'
Error converting value 'E051' to <class 'int'>: invalid literal for int() with base 10: 'E051'
Converting date: '10-11-2019'
Error converting value 'E052' to <class 'int'>: invalid literal for int() with base 10: 'E052'
Converting date: '05-01-2018'
Error converting value 'E053' to <class 'int'>: invalid literal for int() with base 10: 'E053'
Converting date: '20-03-2017'
Error converting value 'E054' to <class 'int'>: invalid literal for int() with base 10: 'E054'
Converting date: '15-06-2020'
Error converting value 'E055' to <class 'int'>: invalid literal for int() with base 10: 'E055'
Converting date: '18-09-2016'
Error converting value 'E056' to <class 'int'>: invalid literal for int() with base 10: 'E056'
Converting date: '25-12-2019'
Error converting value 'E057' to <class 'int'>: invalid literal for int() with base 10: 'E057'
Converting date: '12-02-2018'
Error converting value 'E058' to <class 'int'>: invalid literal for int() with base 10: 'E058'
Converting date: '01-04-2017'
Error converting value 'E059' to <class 'int'>: invalid literal for int() with base 10: 'E059'
Converting date: '15-07-2020'
Error converting value 'E060' to <class 'int'>: invalid literal for int() with base 10: 'E060'
Converting date: '22-10-2016'
Error converting value 'E061' to <class 'int'>: invalid literal for int() with base 10: 'E061'
Converting date: '10-01-2019'
First 5 rows of sales_data:
{'sale_id': 1001, 'date': datetime.datetime(2024, 9, 1, 0, 0), 'customer_id': 'C101', 'product_id': 'P201', 'quantity': 2, 'price': 29.99}
{'sale_id': 1002, 'date': datetime.datetime(2024, 9, 2, 0, 0), 'customer_id': 'C102', 'product_id': 'P202', 'quantity': 1, 'price': 49.99}
{'sale_id': 1003, 'date': datetime.datetime(2024, 9, 2, 0, 0), 'customer_id': 'C103', 'product_id': 'P203', 'quantity': 3, 'price': 15.99}
{'sale_id': 1004, 'date': datetime.datetime(2024, 9, 3, 0, 0), 'customer_id': 'C101', 'product_id': 'P204', 'quantity': 1, 'price': 99.99}
{'sale_id': 1005, 'date': datetime.datetime(2024, 9, 4, 0, 0), 'customer_id': 'C104', 'product_id': 'P201', 'quantity': 2, 'price': 29.99}

First 5 rows of products_data:
{'product_id': 'P201', 'product_name': 'Wireless Mouse', 'category': 'Electronics', 'cost_price': 20.0}
{'product_id': 'P202', 'product_name': 'LED Desk Lamp', 'category': 'Home & Office', 'cost_price': 35.0}
{'product_id': 'P203', 'product_name': 'Notebook Set', 'category': 'Stationery', 'cost_price': 10.0}
{'product_id': 'P204', 'product_name': 'Bluetooth Speaker', 'category': 'Electronics', 'cost_price': 75.0}
{'product_id': 'P205', 'product_name': 'Ergonomic Chair', 'category': 'Furniture', 'cost_price': 150.0}

First 5 rows of customers_data:
{'customer_id': 'C101', 'name': 'Alex Johnson', 'email': 'alex.johnson@example.com', 'address': '101 Maple Street', 'join_date': datetime.datetime(2023, 1, 15, 0, 0)}
{'customer_id': 'C102', 'name': 'Emily Davis', 'email': 'emily.davis@example.com', 'address': '202 Oak Avenue', 'join_date': datetime.datetime(2023, 1, 22, 0, 0)}
{'customer_id': 'C103', 'name': 'Michael Brown', 'email': 'michael.brown@example.com', 'address': '303 Pine Road', 'join_date': datetime.datetime(2023, 1, 29, 0, 0)}
{'customer_id': 'C104', 'name': 'Sophia Wilson', 'email': 'sophia.wilson@example.com', 'address': '404 Cedar Lane', 'join_date': datetime.datetime(2023, 2, 5, 0, 0)}
{'customer_id': 'C105', 'name': 'Daniel Smith', 'email': 'daniel.smith@example.com', 'address': '505 Birch Drive', 'join_date': datetime.datetime(2023, 2, 12, 0, 0)}

First 5 rows of employees_data:
{'employee_id': None, 'name': 'Emily Johnson', 'department': 'Sales', 'hire_date': datetime.datetime(2018, 1, 15, 0, 0), 'salary': 65000.0}
{'employee_id': None, 'name': 'Michael Smith', 'department': 'Marketing', 'hire_date': datetime.datetime(2019, 3, 22, 0, 0), 'salary': 60000.0}
{'employee_id': None, 'name': 'Jessica Williams', 'department': 'Finance', 'hire_date': datetime.datetime(2017, 6, 10, 0, 0), 'salary': 70000.0}
{'employee_id': None, 'name': 'David Brown', 'department': 'IT', 'hire_date': datetime.datetime(2020, 8, 5, 0, 0), 'salary': 75000.0}
{'employee_id': None, 'name': 'Sarah Davis', 'department': 'Human Resources', 'hire_date': datetime.datetime(2016, 11, 30, 0, 0), 'salary': 68000.0}

In [6]:
#Integrating sales data with products_data and customers_data.Also, calculating derived fields like total sale amount and profit margin.
def integrate_data(sales_data, products_data, customers_data):
    # Create lookup dictionaries for products, customers, and employees
    product_lookup = {p['product_id']: p for p in products_data}
    customer_lookup = {c['customer_id']: c for c in customers_data}

    integrated_data = []
    for sale in sales_data:
        product = product_lookup.get(sale['product_id'], {})
        customer = customer_lookup.get(sale['customer_id'], {})
         # Employee info cant be retrieved as there is nothing common in sales and employee files.

        if product and customer:  # Ensure all mappings exist
            total_amount = int(sale['quantity']) * float(sale['price'])
            cost_price = product['cost_price']
            profit_margin = (total_amount - (cost_price * int(sale['quantity']))) / total_amount

            integrated_data.append({
                "sale_id": sale['sale_id'],
                "date": sale['date'],
                "customer_id": sale['customer_id'],
                "quantity": int(sale['quantity']),
                "price": float(sale['price']),
                "product_id": sale['product_id'],
                "product_name": product['product_name'],
                "category": product['category'],
                "customer_name": customer['name'],
                "total_amount": total_amount,
                "profit_margin": profit_margin,
            })

    return integrated_data

# Integrate the data
integrated_sales_data = integrate_data(sales_data, products_data, customers_data)

# Print the first 5 entries of the integrated data
print("Integrated Sales Data (first 5 entries):")
for record in integrated_sales_data[:5]:  # Slicing to get the first 5 records
    print(record)

Integrated Sales Data (first 5 entries):
{'sale_id': 1001, 'date': datetime.datetime(2024, 9, 1, 0, 0), 'customer_id': 'C101', 'quantity': 2, 'price': 29.99, 'product_id': 'P201', 'product_name': 'Wireless Mouse', 'category': 'Electronics', 'customer_name': 'Alex Johnson', 'total_amount': 59.98, 'profit_margin': 0.3331110370123374}
{'sale_id': 1002, 'date': datetime.datetime(2024, 9, 2, 0, 0), 'customer_id': 'C102', 'quantity': 1, 'price': 49.99, 'product_id': 'P202', 'product_name': 'LED Desk Lamp', 'category': 'Home & Office', 'customer_name': 'Emily Davis', 'total_amount': 49.99, 'profit_margin': 0.2998599719943989}
{'sale_id': 1003, 'date': datetime.datetime(2024, 9, 2, 0, 0), 'customer_id': 'C103', 'quantity': 3, 'price': 15.99, 'product_id': 'P203', 'product_name': 'Notebook Set', 'category': 'Stationery', 'customer_name': 'Michael Brown', 'total_amount': 47.97, 'profit_margin': 0.37460913070669166}
{'sale_id': 1004, 'date': datetime.datetime(2024, 9, 3, 0, 0), 'customer_id': 'C101', 'quantity': 1, 'price': 99.99, 'product_id': 'P204', 'product_name': 'Bluetooth Speaker', 'category': 'Electronics', 'customer_name': 'Alex Johnson', 'total_amount': 99.99, 'profit_margin': 0.24992499249924988}
{'sale_id': 1005, 'date': datetime.datetime(2024, 9, 4, 0, 0), 'customer_id': 'C104', 'quantity': 2, 'price': 29.99, 'product_id': 'P201', 'product_name': 'Wireless Mouse', 'category': 'Electronics', 'customer_name': 'Sophia Wilson', 'total_amount': 59.98, 'profit_margin': 0.3331110370123374}

In [11]:
#Creating date dimension with time based attributes

from datetime import datetime, timedelta
import csv

sales_data = read_csv(r'E:\Hero Vired\Python ETL project\sales.csv')


def create_date_dimension(sales_data):
    # Extract the date range from sales data
    min_date = min(datetime.strptime(row['date'], '%d-%m-%Y') for row in sales_data)
    max_date = max(datetime.strptime(row['date'], '%d-%m-%Y') for row in sales_data)

    # Initialize an empty list to hold the date dimension
    date_dimension = []

    # Loop through each date in the range
    current_date = min_date
    while current_date <= max_date:
        # Extract attributes
        year = current_date.year
        month = current_date.month
        month_name = current_date.strftime('%B')
        quarter = (month - 1) // 3 + 1
        day = current_date.day
        day_of_week = current_date.weekday()  # Monday=0, Sunday=6
        day_name = current_date.strftime('%A')
        is_weekend = day_of_week >= 5  # Saturday=5, Sunday=6

        # Append the attributes as a dictionary
        date_dimension.append({
            'date': current_date.strftime('%d-%m-%Y'),  # Format date as string
            'year': year,
            'month': month,
            'month_name': month_name,
            'quarter': quarter,
            'day': day,
            'day_of_week': day_of_week,
            'day_name': day_name,
            'is_weekend': is_weekend
        })

        # Move to the next day
        current_date += timedelta(days=1)

    return date_dimension

# Create the date dimension
date_dimension_list = create_date_dimension(sales_data)



# Print the first 5 entries of the date dimension
print("Date Dimension (first 5 entries):")
for entry in date_dimension_list[:5]:
    print (entry)

Date Dimension (first 5 entries):
{'date': '01-09-2024', 'year': 2024, 'month': 9, 'month_name': 'September', 'quarter': 3, 'day': 1, 'day_of_week': 6, 'day_name': 'Sunday', 'is_weekend': True}
{'date': '02-09-2024', 'year': 2024, 'month': 9, 'month_name': 'September', 'quarter': 3, 'day': 2, 'day_of_week': 0, 'day_name': 'Monday', 'is_weekend': False}
{'date': '03-09-2024', 'year': 2024, 'month': 9, 'month_name': 'September', 'quarter': 3, 'day': 3, 'day_of_week': 1, 'day_name': 'Tuesday', 'is_weekend': False}
{'date': '04-09-2024', 'year': 2024, 'month': 9, 'month_name': 'September', 'quarter': 3, 'day': 4, 'day_of_week': 2, 'day_name': 'Wednesday', 'is_weekend': False}
{'date': '05-09-2024', 'year': 2024, 'month': 9, 'month_name': 'September', 'quarter': 3, 'day': 5, 'day_of_week': 3, 'day_name': 'Thursday', 'is_weekend': False}

In [ ]:
#3. Data Loading
# Function to write a CSV file
def write_csv(file_path, data, fieldnames):
    with open(file_path, mode='w', newline='') as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(data)

# Generate comprehensive sales report
comprehensive_report_path = r'E:\Hero Vired\Python project\comprehensive_sales_report.csv'
write_csv(comprehensive_report_path, integrated_sales_data, integrated_sales_data[0].keys())
print(f"Comprehensive sales report generated at: {comprehensive_report_path}")

# Generate summary report
summary_report = []
summary_lookup = {}

for record in integrated_sales_data:
    customer_id = record['customer_id']
    product_id = record['product_id']
    total_amount = record['total_amount']
    quantity = record['quantity']

    # Create a unique key for each customer-product combination
    key = (customer_id, product_id)

    if key not in summary_lookup:
        summary_lookup[key] = {
            'customer_id': customer_id,
            'customer_name': record['customer_name'],
            'product_id': product_id,
            'product_name': record['product_name'],
            'total_sales': 0,
            'total_quantity': 0
        }

    summary_lookup[key]['total_sales'] += total_amount
    summary_lookup[key]['total_quantity'] += quantity

# Convert summary lookup to a list
for key, summary in summary_lookup.items():
    summary_report.append({
        'customer_id': summary['customer_id'],
        'customer_name': summary['customer_name'],
        'product_id': summary['product_id'],
        'product_name': summary['product_name'],
        'total_sales': summary['total_sales'],
        'total_quantity': summary['total_quantity']
    })

# Write summary report to CSV
summary_report_path = r'E:\Hero Vired\Python project\summary_sales_report.csv'
write_csv(summary_report_path, summary_report, summary_report[0].keys())
print(f"Summary sales report generated at: {summary_report_path}")

In [21]:
#4. Data Analysis

from collections import defaultdict
from datetime import datetime
# Create a lookup dictionary for products
product_lookup = {p['product_id']: p for p in products_data}

# 1. Calculate total sales and profit by product category
category_sales = defaultdict(lambda: {'total_sales': 0, 'total_profit': 0})

for record in integrated_sales_data:
    category = record['category']
    total_amount = record['total_amount']
    
    # Use the product_id to get the product details from the lookup dictionary
    product = product_lookup.get(record['product_id'], {})
    cost_price = float(product.get('cost_price', 0))  # Default to 0 if not found
    profit = total_amount - (cost_price * record['quantity'])

    category_sales[category]['total_sales'] += total_amount
    category_sales[category]['total_profit'] += profit

print("\nTotal Sales and Profit by Product Category:")
for category, values in category_sales.items():
    print(f"Category: {category}, Total Sales: {values['total_sales']:.2f}, Total Profit: {values['total_profit']:.2f}")

# 2. Identify top-selling products
product_sales = defaultdict(lambda: {'total_sales': 0, 'total_quantity': 0})

for record in integrated_sales_data:
    product_id = record['product_id']
    total_amount = record['total_amount']
    quantity = record['quantity']

    product_sales[product_id]['total_sales'] += total_amount
    product_sales[product_id]['total_quantity'] += quantity

top_selling_products = sorted(product_sales.items(), key=lambda x: x[1]['total_sales'], reverse=True)[:5]

print("\nTop-Selling Products:")
for product_id, values in top_selling_products:
    product_name = product_lookup.get(product_id, {}).get('product_name', 'Unknown')  # Use lookup dictionary
    print(f"Product: {product_name}, Total Sales: {values['total_sales']:.2f}, Total Quantity: {values['total_quantity']}")

# 2. Identify key customers
customer_sales = defaultdict(lambda: {'total_sales': 0, 'total_quantity': 0})

for record in integrated_sales_data:
    customer_id = record['customer_id']
    total_amount = record['total_amount']
    quantity = record['quantity']

    customer_sales[customer_id]['total_sales'] += total_amount
    customer_sales[customer_id]['total_quantity'] += quantity

key_customers = sorted(customer_sales.items(), key=lambda x: x[1]['total_sales'], reverse=True)[:5]

print("\nKey Customers:")
for customer_id, values in key_customers:
    customer_name = next((c['name'] for c in customers_data if c['customer_id'] == customer_id), "Unknown")
    print(f"Customer ID: {customer_id}, Name: {customer_name}, Total Sales: {values['total_sales']:.2f}, Total Quantity: {values['total_quantity']}")
# 3. Analyze sales trends over time (daily, monthly, quarterly).
    
from collections import defaultdict
from datetime import datetime

# Initialize dictionaries to hold sales data for trends
daily_sales = defaultdict(float)
monthly_sales = defaultdict(float)
quarterly_sales = defaultdict(float)

# Iterate through the integrated sales data to calculate sales trends
for record in integrated_sales_data:
    date = record.get('date')  # Safely get the date
    if date is None:
        print("Warning: Date is None for record:", record)
        continue  # Skip this record

    # Check if date is already a datetime object
    if isinstance(date, datetime):
        date_obj = date  # Use the existing datetime object
    else:
        # Convert date from dd-mm-yyyy to datetime object
        try:
            date_obj = datetime.strptime(date, '%d-%m-%Y')  # Assuming input is in dd-mm-yyyy format
        except ValueError as e:
            print(f"Error parsing date '{date}': {e}")
            continue  # Skip this record if date parsing fails

    # Format the date for daily sales
    formatted_date = date_obj.strftime('%Y-%m-%d')

    # Daily sales
    daily_sales[formatted_date] += record['total_amount']

    # Monthly sales
    month = formatted_date[:7]  # Extract YYYY-MM format
    monthly_sales[month] += record['total_amount']

    # Quarterly sales
    year = formatted_date[:4]
    month_num = int(formatted_date[5:7])
    quarter = (month_num - 1) // 3 + 1
    quarterly_key = f"{year}-Q{quarter}"
    quarterly_sales[quarterly_key] += record['total_amount']
    
print("\nBrief summary report")
# Print daily sales trends
print("\nDaily Sales Trends:")
for date, total in sorted(daily_sales.items()):
    print(f"Date: {date}, Total Sales: {total:.2f}")

# Print monthly sales trends
print("\nMonthly Sales Trends:")
for month, total in sorted(monthly_sales.items()):
    print(f"Month: {month}, Total Sales: {total:.2f}")

# Print quarterly sales trends
print("\nQuarterly Sales Trends:")
for quarter, total in sorted(quarterly_sales.items()):
    print(f"Quarter: {quarter}, Total Sales: {total:.2f}")

Total Sales and Profit by Product Category:
Category: Electronics, Total Sales: 12228.14, Total Profit: 3283.14
Category: Home & Office, Total Sales: 4649.07, Total Profit: 1394.07
Category: Stationery, Total Sales: 1439.10, Total Profit: 539.10

Top-Selling Products:
Product: Bluetooth Speaker, Total Sales: 9499.05, Total Quantity: 95
Product: LED Desk Lamp, Total Sales: 4649.07, Total Quantity: 93
Product: Wireless Mouse, Total Sales: 2729.09, Total Quantity: 91
Product: Notebook Set, Total Sales: 1439.10, Total Quantity: 90

Key Customers:
Customer ID: C123, Name: Jackson Carter, Total Sales: 999.90, Total Quantity: 10
Customer ID: C111, Name: William Young, Total Sales: 799.92, Total Quantity: 8
Customer ID: C107, Name: Matthew Clark, Total Sales: 599.94, Total Quantity: 6
Customer ID: C119, Name: Jacob Adams, Total Sales: 599.94, Total Quantity: 6
Customer ID: C103, Name: Michael Brown, Total Sales: 547.92, Total Quantity: 8

Brief summary report

Daily Sales Trends:
Date: 2024-09-01, Total Sales: 59.98
Date: 2024-09-02, Total Sales: 97.96
Date: 2024-09-03, Total Sales: 99.99
Date: 2024-09-04, Total Sales: 59.98
Date: 2024-09-05, Total Sales: 199.96
Date: 2024-09-06, Total Sales: 15.99
Date: 2024-09-07, Total Sales: 499.95
Date: 2024-09-08, Total Sales: 59.98
Date: 2024-09-09, Total Sales: 149.97
Date: 2024-09-10, Total Sales: 31.98
Date: 2024-09-11, Total Sales: 399.96
Date: 2024-09-12, Total Sales: 29.99
Date: 2024-09-13, Total Sales: 249.95
Date: 2024-09-14, Total Sales: 47.97
Date: 2024-09-15, Total Sales: 199.98
Date: 2024-09-16, Total Sales: 119.96
Date: 2024-09-17, Total Sales: 49.99
Date: 2024-09-18, Total Sales: 79.95
Date: 2024-09-19, Total Sales: 299.97
Date: 2024-09-20, Total Sales: 59.98
Date: 2024-09-21, Total Sales: 199.96
Date: 2024-09-22, Total Sales: 15.99
Date: 2024-09-23, Total Sales: 499.95
Date: 2024-09-24, Total Sales: 89.97
Date: 2024-09-25, Total Sales: 99.98
Date: 2024-09-26, Total Sales: 63.96
Date: 2024-09-27, Total Sales: 99.99
Date: 2024-09-28, Total Sales: 149.95
Date: 2024-09-29, Total Sales: 149.97
Date: 2024-09-30, Total Sales: 31.98
Date: 2024-10-01, Total Sales: 399.96
Date: 2024-10-02, Total Sales: 29.99
Date: 2024-10-03, Total Sales: 249.95
Date: 2024-10-04, Total Sales: 47.97
Date: 2024-10-05, Total Sales: 199.98
Date: 2024-10-06, Total Sales: 119.96
Date: 2024-10-07, Total Sales: 49.99
Date: 2024-10-08, Total Sales: 79.95
Date: 2024-10-09, Total Sales: 299.97
Date: 2024-10-10, Total Sales: 59.98
Date: 2024-10-11, Total Sales: 199.96
Date: 2024-10-12, Total Sales: 15.99
Date: 2024-10-13, Total Sales: 499.95
Date: 2024-10-14, Total Sales: 89.97
Date: 2024-10-15, Total Sales: 99.98
Date: 2024-10-16, Total Sales: 63.96
Date: 2024-10-17, Total Sales: 99.99
Date: 2024-10-18, Total Sales: 149.95
Date: 2024-10-19, Total Sales: 149.97
Date: 2024-10-20, Total Sales: 31.98
Date: 2024-10-21, Total Sales: 399.96
Date: 2024-10-22, Total Sales: 29.99
Date: 2024-10-23, Total Sales: 249.95
Date: 2024-10-24, Total Sales: 47.97
Date: 2024-10-25, Total Sales: 199.98
Date: 2024-10-26, Total Sales: 119.96
Date: 2024-10-27, Total Sales: 49.99
Date: 2024-10-28, Total Sales: 79.95
Date: 2024-10-29, Total Sales: 299.97
Date: 2024-10-30, Total Sales: 59.98
Date: 2024-10-31, Total Sales: 199.96
Date: 2024-11-01, Total Sales: 15.99
Date: 2024-11-02, Total Sales: 499.95
Date: 2024-11-03, Total Sales: 89.97
Date: 2024-11-04, Total Sales: 99.98
Date: 2024-11-05, Total Sales: 63.96
Date: 2024-11-06, Total Sales: 99.99
Date: 2024-11-07, Total Sales: 149.95
Date: 2024-11-08, Total Sales: 149.97
Date: 2024-11-09, Total Sales: 31.98
Date: 2024-11-10, Total Sales: 399.96
Date: 2024-11-11, Total Sales: 29.99
Date: 2024-11-12, Total Sales: 249.95
Date: 2024-11-13, Total Sales: 47.97
Date: 2024-11-14, Total Sales: 199.98
Date: 2024-11-15, Total Sales: 119.96
Date: 2024-11-16, Total Sales: 49.99
Date: 2024-11-17, Total Sales: 79.95
Date: 2024-11-18, Total Sales: 299.97
Date: 2024-11-19, Total Sales: 59.98
Date: 2024-11-20, Total Sales: 199.96
Date: 2024-11-21, Total Sales: 15.99
Date: 2024-11-22, Total Sales: 499.95
Date: 2024-11-23, Total Sales: 89.97
Date: 2024-11-24, Total Sales: 99.98
Date: 2024-11-25, Total Sales: 63.96
Date: 2024-11-26, Total Sales: 99.99
Date: 2024-11-27, Total Sales: 149.95
Date: 2024-11-28, Total Sales: 149.97
Date: 2024-11-29, Total Sales: 31.98
Date: 2024-11-30, Total Sales: 399.96
Date: 2024-12-01, Total Sales: 29.99
Date: 2024-12-02, Total Sales: 249.95
Date: 2024-12-03, Total Sales: 47.97
Date: 2024-12-04, Total Sales: 199.98
Date: 2024-12-05, Total Sales: 119.96
Date: 2024-12-06, Total Sales: 49.99
Date: 2024-12-07, Total Sales: 79.95
Date: 2024-12-08, Total Sales: 299.97
Date: 2024-12-09, Total Sales: 59.98
Date: 2024-12-10, Total Sales: 199.96
Date: 2024-12-11, Total Sales: 15.99
Date: 2024-12-12, Total Sales: 499.95
Date: 2024-12-13, Total Sales: 89.97
Date: 2024-12-14, Total Sales: 99.98
Date: 2024-12-15, Total Sales: 63.96
Date: 2024-12-16, Total Sales: 99.99
Date: 2024-12-17, Total Sales: 149.95
Date: 2024-12-18, Total Sales: 149.97
Date: 2024-12-19, Total Sales: 31.98
Date: 2024-12-20, Total Sales: 399.96
Date: 2024-12-21, Total Sales: 29.99
Date: 2024-12-22, Total Sales: 249.95
Date: 2024-12-23, Total Sales: 47.97
Date: 2024-12-24, Total Sales: 199.98
Date: 2024-12-25, Total Sales: 119.96
Date: 2024-12-26, Total Sales: 49.99
Date: 2024-12-27, Total Sales: 79.95
Date: 2024-12-28, Total Sales: 299.97
Date: 2024-12-29, Total Sales: 59.98
Date: 2024-12-30, Total Sales: 199.96
Date: 2024-12-31, Total Sales: 15.99
Date: 2025-01-01, Total Sales: 499.95
Date: 2025-01-02, Total Sales: 89.97

Monthly Sales Trends:
Month: 2024-09, Total Sales: 4215.14
Month: 2024-10, Total Sales: 4677.06
Month: 2024-11, Total Sales: 4541.10
Month: 2024-12, Total Sales: 4293.09
Month: 2025-01, Total Sales: 589.92

Quarterly Sales Trends:
Quarter: 2024-Q3, Total Sales: 4215.14
Quarter: 2024-Q4, Total Sales: 13511.25
Quarter: 2025-Q1, Total Sales: 589.92